// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class UpdateFiles {
    "addFiles": string[];
    "deleteFiles": string[];
    "modifyFiles": string[];

    /** Creates a new UpdateFiles instance. */
    constructor($$source: Partial<UpdateFiles> = {}) {
        if (!("addFiles" in $$source)) {
            this["addFiles"] = [];
        }
        if (!("deleteFiles" in $$source)) {
            this["deleteFiles"] = [];
        }
        if (!("modifyFiles" in $$source)) {
            this["modifyFiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateFiles instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateFiles {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addFiles" in $$parsedSource) {
            $$parsedSource["addFiles"] = $$createField0_0($$parsedSource["addFiles"]);
        }
        if ("deleteFiles" in $$parsedSource) {
            $$parsedSource["deleteFiles"] = $$createField1_0($$parsedSource["deleteFiles"]);
        }
        if ("modifyFiles" in $$parsedSource) {
            $$parsedSource["modifyFiles"] = $$createField2_0($$parsedSource["modifyFiles"]);
        }
        return new UpdateFiles($$parsedSource as Partial<UpdateFiles>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
